version: '3'
services:
  dcrdex-postgresql:
    image: postgres:12.2
    environment:
      POSTGRES_USER: dcrdex
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: dcrdex_simnet
  dcrdex-bitcoind:
    image: dcrdex-bitcoind
  dcrdex-kube:
    image: dcrdex-kube
    ports:
      - 5758:5758